{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"SUN",
            "address":"TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9",
            "chainId":1,
            "decimals":18,
            "name":"SUN TOKEN",
            "logoURI":"https://coin.top/production/logo/SUNLogo.178d4636.png"
        },
        {
            "symbol":"BTC",
            "address":"TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9",
            "chainId":1,
            "decimals":8,
            "name":"Bitcoin",
            "logoURI":"https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
        },
        {
            "symbol":"KIi",
            "address":"TXxD9SVQeuArQrXkpGJjFVHjD53rma8a5e",
            "chainId":1,
            "decimals":18,
            "name":"Kitoken",
            "logoURI":"https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
        },
        {
            "symbol":"HT",
            "address":"TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h",
            "chainId":1,
            "decimals":18,
            "name":"HuobiToken",
            "logoURI":"https://coin.top/production/logo/TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h.png"
        }
    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}
